In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/air-quality-and-pollution-assessment/updated_pollution_dataset.csv


In [2]:
import numpy as np 
import pandas as pd 
from sklearn.model_selection import train_test_split 
from sklearn.metrics import accuracy_score, classification_report
from sklearn.linear_model import LogisticRegression
import warnings 
warnings.filterwarnings('ignore')
from sklearn.ensemble import RandomForestClassifier, BaggingClassifier, AdaBoostClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB 
from sklearn.tree import DecisionTreeClassifier

In [3]:
df = pd.read_csv("/kaggle/input/air-quality-and-pollution-assessment/updated_pollution_dataset.csv")
df.head()

Temperature  Humidity  PM2.5  PM10   NO2   SO2    CO  \
0         29.8      59.1    5.2  17.9  18.9   9.2  1.72   
1         28.3      75.6    2.3  12.2  30.8   9.7  1.64   
2         23.1      74.7   26.7  33.8  24.4  12.6  1.63   
3         27.1      39.1    6.1   6.3  13.5   5.3  1.15   
4         26.5      70.7    6.9  16.0  21.9   5.6  1.01   

   Proximity_to_Industrial_Areas  Population_Density Air Quality  
0                            6.3                 319    Moderate  
1                            6.0                 611    Moderate  
2                            5.2                 619    Moderate  
3                           11.1                 551        Good  
4                           12.7                 303        Good

In [4]:
df['Air Quality'].value_counts()

Air Quality
Good         2000
Moderate     1500
Poor         1000
Hazardous     500
Name: count, dtype: int64

In [5]:
from sklearn.preprocessing import LabelEncoder

enc = LabelEncoder()
df['Air Quality'] = enc.fit_transform(df['Air Quality'])

In [6]:
df['Air Quality'].value_counts()

Air Quality
0    2000
2    1500
3    1000
1     500
Name: count, dtype: int64

  0 -------> Good

  
  1 -------> Moderate  

  
  2 -------> Poor

  
  3 -------> Hazardous

In [7]:
X = df.drop('Air Quality', axis=1) 
y = df['Air Quality']

In [8]:
# Split the data into training and testing sets 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [9]:
model = LogisticRegression() 
model.fit(X_train, y_train)

LogisticRegression()

In [10]:
y_pred = model.predict(X_test)

In [11]:
y_pred

array([1, 0, 0, 1, 0, 3, 0, 0, 0, 2, 3, 0, 1, 0, 2, 0, 0, 0, 2, 2, 0, 0,
       2, 2, 0, 3, 0, 2, 2, 2, 0, 3, 2, 2, 2, 2, 2, 2, 2, 0, 3, 2, 1, 0,
       0, 0, 3, 1, 0, 0, 2, 0, 0, 0, 0, 3, 3, 2, 1, 0, 0, 0, 0, 2, 0, 1,
       3, 0, 2, 2, 0, 0, 2, 0, 0, 2, 2, 2, 0, 0, 0, 2, 3, 0, 2, 2, 2, 2,
       2, 1, 2, 0, 0, 2, 3, 2, 2, 0, 3, 0, 1, 2, 3, 2, 1, 0, 0, 0, 2, 2,
       1, 2, 2, 0, 2, 3, 3, 0, 0, 0, 2, 3, 2, 2, 3, 0, 2, 2, 0, 0, 2, 0,
       2, 0, 2, 2, 0, 0, 0, 0, 0, 2, 0, 0, 2, 2, 3, 0, 2, 2, 3, 2, 2, 0,
       0, 3, 2, 2, 2, 2, 1, 0, 0, 3, 1, 3, 0, 0, 0, 0, 2, 1, 0, 2, 0, 0,
       0, 2, 0, 3, 1, 0, 3, 0, 0, 3, 0, 0, 0, 0, 2, 3, 2, 3, 2, 2, 3, 3,
       1, 3, 0, 0, 2, 2, 0, 0, 0, 2, 0, 0, 0, 0, 3, 2, 3, 2, 2, 2, 0, 1,
       0, 2, 0, 2, 0, 2, 1, 3, 2, 0, 0, 0, 0, 0, 0, 2, 0, 2, 3, 3, 2, 0,
       2, 3, 0, 2, 0, 0, 0, 0, 2, 2, 0, 3, 3, 1, 0, 0, 3, 3, 0, 2, 0, 1,
       0, 2, 3, 1, 2, 2, 2, 2, 2, 2, 3, 3, 2, 0, 3, 0, 3, 0, 0, 3, 2, 0,
       3, 2, 0, 2, 2, 3, 0, 0, 1, 2, 2, 2, 2, 0, 2,

In [12]:
accuracy = accuracy_score(y_test,y_pred)
class_report = classification_report(y_test,y_pred)

In [13]:
print(f"Logistic Regression Accuracy : {accuracy}")
print(f"Classification Report:{class_report}")

Logistic Regression Accuracy : 0.75
Classification Report:              precision    recall  f1-score   support

           0       0.97      0.96      0.97       409
           1       0.45      0.37      0.40       111
           2       0.74      0.79      0.76       294
           3       0.44      0.45      0.45       186

    accuracy                           0.75      1000
   macro avg       0.65      0.64      0.64      1000
weighted avg       0.75      0.75      0.75      1000



In [14]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)

RandomForestClassifier()

In [15]:
rf_predictions = rf.predict(X_test)

In [16]:
rf_predictions

array([1, 0, 2, 1, 0, 1, 0, 0, 0, 2, 2, 0, 1, 0, 2, 0, 0, 0, 2, 3, 0, 0,
       3, 2, 0, 3, 0, 0, 2, 2, 0, 3, 2, 2, 2, 3, 2, 2, 2, 0, 3, 2, 1, 0,
       0, 2, 2, 3, 0, 0, 2, 0, 0, 0, 0, 2, 1, 2, 3, 0, 0, 0, 0, 2, 0, 3,
       3, 0, 2, 2, 0, 0, 3, 0, 0, 2, 2, 2, 0, 0, 0, 1, 3, 0, 2, 2, 1, 2,
       2, 1, 2, 0, 0, 3, 3, 2, 2, 0, 3, 0, 1, 2, 2, 2, 1, 0, 0, 0, 2, 0,
       2, 2, 2, 0, 2, 3, 1, 0, 0, 0, 2, 2, 3, 2, 3, 0, 2, 2, 0, 0, 2, 0,
       3, 0, 2, 2, 0, 0, 2, 0, 0, 2, 0, 0, 2, 2, 1, 0, 2, 2, 3, 3, 3, 0,
       0, 3, 2, 2, 2, 2, 1, 0, 2, 1, 3, 2, 0, 0, 0, 0, 2, 3, 0, 1, 0, 0,
       0, 2, 0, 3, 3, 0, 2, 0, 0, 3, 0, 0, 0, 0, 1, 1, 2, 1, 2, 2, 1, 1,
       3, 3, 0, 0, 2, 2, 0, 0, 0, 2, 0, 0, 0, 0, 3, 2, 2, 2, 2, 3, 0, 1,
       0, 2, 0, 2, 0, 2, 1, 1, 2, 0, 0, 0, 0, 0, 0, 3, 0, 3, 3, 2, 2, 0,
       2, 1, 0, 2, 0, 0, 0, 0, 2, 2, 0, 1, 3, 3, 0, 0, 1, 3, 0, 2, 0, 1,
       0, 2, 3, 3, 2, 0, 2, 2, 2, 0, 1, 1, 2, 0, 3, 0, 1, 0, 0, 3, 2, 0,
       3, 2, 0, 2, 2, 1, 0, 0, 2, 2, 2, 2, 2, 0, 2,

In [17]:
print("Random Forest Accuracy:", accuracy_score(y_test, rf_predictions))
print(classification_report(y_test, rf_predictions))

Random Forest Accuracy: 0.958
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       409
           1       0.91      0.87      0.89       111
           2       0.97      0.97      0.97       294
           3       0.88      0.90      0.89       186

    accuracy                           0.96      1000
   macro avg       0.94      0.94      0.94      1000
weighted avg       0.96      0.96      0.96      1000



In [18]:
bagging = BaggingClassifier(base_estimator=DecisionTreeClassifier(), n_estimators=50, random_state=42)
bagging.fit(X_train, y_train)

BaggingClassifier(base_estimator=DecisionTreeClassifier(), n_estimators=50,
                  random_state=42)

In [19]:
bagging_predictions = bagging.predict(X_test)

In [20]:
bagging_predictions

array([1, 0, 2, 3, 0, 1, 0, 0, 0, 2, 2, 0, 1, 0, 2, 0, 0, 0, 2, 3, 0, 0,
       3, 2, 0, 3, 0, 0, 2, 2, 0, 3, 2, 2, 2, 3, 2, 2, 2, 0, 3, 2, 1, 0,
       0, 2, 2, 3, 0, 0, 2, 0, 0, 0, 0, 2, 1, 2, 3, 0, 0, 0, 0, 2, 0, 3,
       3, 0, 2, 2, 0, 0, 3, 0, 0, 2, 2, 2, 0, 0, 0, 3, 3, 0, 2, 2, 1, 2,
       2, 3, 2, 0, 0, 3, 3, 2, 2, 0, 3, 0, 1, 2, 2, 2, 1, 0, 0, 0, 2, 0,
       2, 2, 2, 0, 2, 3, 1, 0, 0, 0, 2, 2, 3, 2, 3, 0, 2, 2, 0, 0, 2, 0,
       3, 0, 2, 2, 0, 0, 2, 0, 0, 2, 0, 0, 2, 2, 1, 0, 2, 2, 3, 3, 3, 0,
       0, 3, 2, 2, 2, 2, 1, 0, 2, 1, 3, 2, 0, 0, 0, 0, 2, 3, 0, 1, 0, 0,
       0, 2, 0, 3, 3, 0, 2, 0, 0, 3, 0, 0, 0, 0, 1, 1, 2, 1, 2, 2, 1, 1,
       3, 3, 0, 0, 2, 2, 0, 0, 0, 2, 0, 0, 0, 0, 3, 2, 2, 2, 2, 3, 0, 1,
       0, 2, 0, 2, 0, 2, 1, 1, 2, 0, 0, 0, 0, 0, 0, 3, 0, 3, 3, 2, 2, 0,
       2, 1, 0, 2, 0, 0, 0, 0, 2, 2, 0, 1, 3, 3, 0, 0, 1, 3, 0, 2, 0, 1,
       0, 2, 3, 3, 2, 0, 2, 2, 2, 0, 1, 1, 2, 0, 3, 0, 1, 0, 0, 3, 2, 0,
       3, 2, 0, 2, 2, 1, 0, 0, 2, 2, 2, 2, 2, 0, 2,

In [21]:
print("Bagging Accuracy:", accuracy_score(y_test, bagging_predictions))
print(classification_report(y_test, bagging_predictions))

Bagging Accuracy: 0.951
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       409
           1       0.90      0.86      0.88       111
           2       0.96      0.97      0.96       294
           3       0.87      0.88      0.87       186

    accuracy                           0.95      1000
   macro avg       0.93      0.92      0.93      1000
weighted avg       0.95      0.95      0.95      1000



In [22]:
boosting = AdaBoostClassifier(n_estimators=50, random_state=42)
boosting.fit(X_train, y_train)

AdaBoostClassifier(random_state=42)

In [23]:
boosting_predictions = boosting.predict(X_test)

In [24]:
boosting_predictions

array([1, 0, 0, 1, 0, 1, 0, 0, 0, 2, 3, 0, 1, 0, 2, 0, 0, 0, 3, 3, 0, 0,
       2, 2, 0, 3, 0, 0, 2, 2, 0, 3, 2, 3, 2, 3, 2, 3, 2, 0, 3, 3, 1, 0,
       0, 2, 2, 3, 0, 0, 2, 0, 0, 0, 0, 2, 1, 2, 3, 0, 0, 0, 0, 2, 0, 1,
       3, 0, 2, 2, 0, 0, 3, 0, 0, 2, 2, 2, 0, 0, 0, 1, 1, 0, 2, 2, 3, 2,
       2, 1, 2, 0, 0, 3, 3, 2, 2, 0, 3, 0, 1, 3, 2, 2, 1, 0, 0, 0, 2, 0,
       2, 2, 2, 0, 2, 3, 1, 0, 0, 0, 2, 2, 2, 2, 3, 0, 2, 2, 0, 0, 2, 0,
       1, 0, 2, 2, 0, 0, 2, 0, 0, 2, 0, 0, 2, 3, 1, 0, 2, 2, 1, 2, 2, 0,
       0, 1, 2, 2, 2, 2, 1, 0, 2, 1, 3, 3, 0, 0, 0, 0, 2, 1, 0, 1, 0, 0,
       0, 2, 0, 3, 3, 0, 2, 0, 0, 2, 0, 0, 0, 0, 1, 3, 2, 1, 3, 3, 1, 1,
       3, 3, 0, 0, 2, 3, 0, 0, 0, 2, 0, 0, 0, 0, 3, 2, 2, 2, 2, 2, 0, 1,
       0, 2, 0, 2, 0, 2, 1, 1, 2, 0, 0, 0, 0, 0, 0, 3, 0, 3, 1, 3, 2, 0,
       2, 1, 0, 2, 0, 0, 0, 0, 2, 2, 0, 1, 3, 3, 0, 0, 1, 3, 0, 2, 0, 1,
       0, 2, 1, 3, 2, 0, 2, 0, 2, 0, 1, 1, 2, 0, 3, 0, 1, 0, 0, 3, 2, 0,
       3, 3, 0, 2, 3, 1, 0, 0, 2, 2, 3, 2, 2, 0, 2,

In [25]:
print("Boosting Accuracy:", accuracy_score(y_test, boosting_predictions))
print(classification_report(y_test, boosting_predictions))

Boosting Accuracy: 0.859
              precision    recall  f1-score   support

           0       0.99      1.00      0.99       409
           1       0.70      0.75      0.72       111
           2       0.92      0.81      0.86       294
           3       0.62      0.70      0.66       186

    accuracy                           0.86      1000
   macro avg       0.81      0.81      0.81      1000
weighted avg       0.87      0.86      0.86      1000



In [26]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [27]:
knn_predictions = knn.predict(X_test)

In [28]:
knn_predictions

array([1, 0, 0, 1, 0, 1, 0, 0, 0, 2, 2, 0, 3, 0, 2, 0, 0, 0, 2, 3, 0, 0,
       2, 2, 0, 3, 0, 0, 2, 0, 0, 3, 3, 2, 3, 3, 2, 2, 2, 0, 3, 2, 1, 0,
       0, 2, 2, 2, 0, 0, 3, 0, 0, 0, 0, 2, 1, 3, 2, 0, 0, 0, 0, 2, 0, 1,
       3, 0, 2, 2, 0, 0, 2, 0, 2, 2, 2, 2, 0, 0, 0, 3, 3, 0, 2, 2, 3, 2,
       0, 1, 2, 2, 0, 3, 2, 2, 2, 0, 2, 0, 1, 0, 3, 0, 2, 0, 0, 0, 2, 0,
       2, 2, 2, 0, 2, 1, 1, 0, 0, 0, 0, 2, 2, 2, 2, 0, 0, 2, 0, 2, 0, 0,
       3, 0, 2, 2, 0, 0, 2, 0, 0, 2, 0, 0, 2, 2, 1, 0, 3, 3, 2, 2, 2, 0,
       0, 3, 2, 3, 2, 0, 3, 0, 2, 1, 3, 3, 0, 0, 0, 0, 2, 3, 0, 1, 0, 0,
       0, 2, 0, 3, 2, 0, 2, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 3, 0, 2, 1, 2,
       1, 3, 0, 0, 2, 2, 0, 0, 0, 2, 0, 0, 0, 0, 3, 2, 3, 2, 2, 1, 0, 3,
       0, 2, 0, 2, 0, 2, 3, 1, 2, 0, 0, 0, 0, 2, 0, 2, 0, 3, 3, 2, 2, 0,
       2, 3, 0, 2, 2, 0, 0, 0, 2, 2, 0, 1, 2, 3, 0, 0, 1, 2, 0, 0, 0, 3,
       0, 2, 3, 3, 2, 0, 2, 2, 2, 0, 3, 1, 0, 0, 3, 0, 3, 0, 0, 2, 2, 0,
       1, 2, 0, 0, 0, 3, 0, 0, 2, 2, 2, 2, 2, 0, 2,

In [29]:
print("KNN Accuracy:", accuracy_score(y_test, knn_predictions))
print(classification_report(y_test, knn_predictions))

KNN Accuracy: 0.783
              precision    recall  f1-score   support

           0       0.91      0.97      0.94       409
           1       0.73      0.46      0.56       111
           2       0.75      0.78      0.76       294
           3       0.56      0.58      0.57       186

    accuracy                           0.78      1000
   macro avg       0.74      0.70      0.71      1000
weighted avg       0.78      0.78      0.78      1000



In [30]:
nb = GaussianNB()
nb.fit(X_train, y_train)

GaussianNB()

In [31]:
nb_predictions = nb.predict(X_test)

In [32]:
nb_predictions 

array([1, 0, 2, 1, 0, 1, 0, 0, 0, 2, 2, 0, 1, 0, 2, 0, 0, 0, 2, 3, 0, 0,
       3, 2, 0, 3, 0, 0, 2, 2, 0, 3, 3, 2, 2, 2, 2, 2, 2, 0, 3, 2, 1, 0,
       0, 2, 2, 3, 0, 0, 2, 0, 0, 0, 0, 2, 1, 2, 3, 0, 0, 0, 0, 2, 0, 3,
       3, 0, 2, 2, 0, 0, 3, 0, 0, 2, 2, 2, 0, 0, 0, 1, 3, 0, 2, 2, 1, 2,
       2, 3, 2, 2, 0, 3, 3, 2, 2, 0, 3, 0, 1, 2, 3, 2, 1, 0, 0, 0, 2, 0,
       2, 2, 2, 0, 2, 3, 1, 0, 0, 0, 2, 2, 3, 2, 3, 0, 2, 2, 0, 0, 2, 0,
       3, 0, 2, 2, 0, 0, 2, 0, 0, 2, 0, 0, 2, 2, 1, 0, 2, 2, 3, 3, 3, 0,
       0, 3, 2, 2, 2, 2, 1, 0, 2, 1, 1, 3, 0, 0, 0, 0, 2, 3, 0, 1, 0, 0,
       0, 2, 0, 3, 3, 0, 3, 0, 0, 1, 0, 0, 0, 0, 1, 1, 2, 3, 2, 2, 1, 3,
       3, 3, 0, 0, 2, 2, 0, 0, 0, 2, 0, 0, 0, 0, 3, 2, 3, 2, 2, 3, 0, 1,
       0, 2, 0, 2, 0, 2, 3, 3, 2, 0, 0, 0, 0, 2, 0, 3, 0, 3, 3, 2, 2, 0,
       2, 1, 0, 0, 0, 0, 0, 0, 2, 2, 0, 3, 3, 3, 0, 0, 1, 3, 0, 2, 0, 1,
       0, 2, 3, 3, 2, 0, 2, 2, 2, 0, 3, 1, 2, 0, 3, 0, 1, 0, 0, 3, 2, 0,
       3, 2, 0, 2, 2, 1, 0, 0, 2, 2, 2, 2, 2, 0, 2,

In [33]:
print("Naive Bayes Accuracy:", accuracy_score(y_test, nb_predictions))
print(classification_report(y_test, nb_predictions))

Naive Bayes Accuracy: 0.926
              precision    recall  f1-score   support

           0       1.00      0.99      0.99       409
           1       0.88      0.77      0.82       111
           2       0.94      0.94      0.94       294
           3       0.79      0.87      0.83       186

    accuracy                           0.93      1000
   macro avg       0.90      0.89      0.89      1000
weighted avg       0.93      0.93      0.93      1000



In [34]:
dt = DecisionTreeClassifier(criterion='entropy')
dt.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy')

In [35]:
dt_predictions = dt.predict(X_test)

In [36]:
dt_predictions

array([1, 0, 0, 1, 0, 1, 0, 0, 0, 2, 2, 0, 3, 0, 2, 0, 0, 0, 2, 3, 0, 0,
       3, 2, 0, 3, 0, 0, 2, 2, 0, 3, 3, 2, 2, 2, 2, 2, 2, 0, 3, 3, 1, 0,
       0, 2, 2, 3, 0, 0, 2, 0, 0, 0, 0, 2, 1, 2, 3, 0, 0, 0, 0, 2, 0, 1,
       3, 0, 2, 2, 0, 0, 3, 0, 0, 2, 2, 2, 0, 0, 0, 3, 3, 0, 2, 2, 1, 2,
       2, 1, 2, 0, 0, 3, 3, 2, 2, 0, 3, 0, 1, 2, 3, 2, 1, 0, 0, 0, 2, 0,
       2, 2, 2, 0, 2, 3, 1, 0, 0, 0, 2, 2, 3, 2, 3, 0, 2, 2, 0, 0, 2, 0,
       1, 0, 2, 2, 0, 0, 2, 0, 0, 2, 0, 0, 2, 2, 1, 0, 2, 3, 3, 3, 3, 0,
       0, 3, 2, 3, 2, 2, 3, 0, 2, 1, 3, 2, 0, 0, 0, 0, 2, 3, 0, 3, 0, 0,
       0, 2, 0, 3, 3, 0, 3, 0, 0, 3, 0, 0, 0, 0, 1, 1, 2, 1, 2, 2, 3, 1,
       3, 3, 0, 0, 2, 3, 0, 0, 0, 2, 0, 0, 0, 0, 3, 2, 2, 2, 2, 3, 0, 1,
       0, 2, 0, 2, 0, 2, 1, 1, 2, 0, 0, 0, 0, 0, 0, 3, 0, 1, 3, 2, 2, 0,
       2, 1, 0, 2, 0, 0, 0, 0, 2, 2, 0, 1, 3, 3, 0, 0, 1, 3, 0, 2, 0, 1,
       0, 2, 3, 1, 2, 0, 2, 2, 2, 0, 1, 1, 2, 0, 3, 0, 1, 0, 0, 3, 2, 0,
       3, 2, 0, 2, 2, 1, 0, 0, 2, 2, 2, 2, 2, 0, 2,

In [37]:
print("Decision Tree Accuracy:", accuracy_score(y_test, dt_predictions))
print(classification_report(y_test, dt_predictions))

Decision Tree Accuracy: 0.925
              precision    recall  f1-score   support

           0       0.99      1.00      1.00       409
           1       0.84      0.79      0.81       111
           2       0.95      0.93      0.94       294
           3       0.79      0.83      0.81       186

    accuracy                           0.93      1000
   macro avg       0.89      0.89      0.89      1000
weighted avg       0.93      0.93      0.93      1000

